[package]
name = "staticlib-fucker"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
ar = "0.9.0"
clap = { version = "4.5.42", features = ["derive"] }
object = { version = "0.37.1", features = ["write_core"] }
rand = "0.9.2"

[profile.release]
lto = "fat"
